export const ENEMIES = {
  DEMON: 'enemies/demon.png',
  DRAGON: 'enemies/dragon.png',
  GHOST: 'enemies/ghost.png',
  GOBLIN: 'enemies/goblin.png',
  ORC: 'enemies/orc.png',
  RAT: 'enemies/rat.png',
  SKELETON: 'enemies/skeleton.png',
  SLIME: 'enemies/slime.png',
  SPIDER: 'enemies/spider.png',
  VAMPIRE: 'enemies/vampire.png',
  WEREWOLF: 'enemies/werewolf.png',
  WITCH: 'enemies/witch.png',
  WIZARD: 'enemies/wizard.png',
  WOLF: 'enemies/wolf.png',
  ZOMBIE: 'enemies/zombie.png',
};
