export const TYPES = {
  // host
  CREATE_ROOM: 'CREATE_ROOM',
  NO_PIN: 'NO_PIN',
  CREATED: 'CREATED',
  START_GAME: 'START_GAME',
  END_GAME: 'END_GAME',
  NEXT_ROUND: 'NEXT_ROUND',

  // player
  JOIN: 'JOIN',
  JOINED: 'JOINED',
  DUPLICATE_NICK: 'DUPLICATE_NICK',
  NO_ROOM: 'NO_ROOM',
  PLAY: 'PLAY',
  ANSWER: 'ANSWER',
  NODE_OPTION: 'NODE_OPTION',
  CHOOSE_NODE: 'CHOOSE_NODE',

  // common
  STARTED: 'STARTED',
  ENDED: 'ENDED',
  RESULTS: 'RESULTS',
  ERROR: 'ERROR',
};
