FROM node:latest as build

COPY package.json package-lock.json ./

RUN npm install 

WORKDIR /app

COPY . .

ENV NODE_ENV=production

RUN npm run build

# Stage 2 

FROM nginx:alpine

COPY --from=build /app/nginx/nginx.conf /etc/nginx/nginx.conf

RUN rm -r /usr/share/nginx/html/*

COPY --from=build /app/dist/frontend /usr/share/nginx/html

EXPOSE 80

ENTRYPOINT [ "nginx", "-g", "deamon off;" ]