package pl.srychert.PartyGamesPlatform.enums;

public enum ItemType {
    HEAL_POTION, RED_BUFF_POTION, BLUE_BUFF_POTION, YELLOW_BUFF_POTION, VIOLET_BUFF_POTION, ORANGE_BUFF_POTION,
    GREEN_BUFF_POTION, WHITE_BUFF_POTION,
//    WEAPON, RELICT
}
